#!/usr/bin/env bash
# GLM-5.2 variant of label-artifact.sh -- see that file for the full rationale.
# Waits for the cowboy-clue HTML to be written, then preserves/labels it with full
# provenance and writes an ARTIFACT-*.md sidecar with measured performance.
set -uo pipefail
R="${1:-/home/user/cowboy-clue benchmark/runs/cowboy-clue-glm52-cmp170hx}"
WAIT_PID="${2:-}"
LABEL="cmp170hx-64gb-unlocked_glm-5.2-UD-Q2_K_XL-mtp_$(date +%Y%m%d)"

find_html() { ls -S "$R"/*.html 2>/dev/null | grep -v '\.original\.html$' | grep -v "_${LABEL}\.html$" | head -1; }

if [[ -n "$WAIT_PID" ]]; then
    echo "[$(date '+%F %T')] waiting for agent PID $WAIT_PID to exit"
    while kill -0 "$WAIT_PID" 2>/dev/null; do sleep 15; done
    echo "[$(date '+%F %T')] agent exited"
fi

echo "[$(date '+%F %T')] looking for an HTML artifact in $R"
for i in $(seq 1 2160); do SRC=$(find_html); [[ -n "${SRC:-}" && -s "$SRC" ]] && break; sleep 10; done
SRC=$(find_html)
[[ -n "${SRC:-}" && -s "$SRC" ]] || { echo "ERROR: no HTML artifact appeared"; exit 1; }

prev=0; for i in $(seq 1 40); do
    cur=$(wc -c < "$SRC"); [[ "$cur" == "$prev" ]] && break; prev=$cur; sleep 15
done
echo "[$(date '+%F %T')] settled on $(basename "$SRC"): $(wc -c < "$SRC") bytes"

BASE="${SRC%.html}"
cp -n "$SRC" "${BASE}.original.html"

GPU=$(nvidia-smi --query-gpu=name,memory.total,vbios_version --format=csv,noheader)
SERIAL=$(nvidia-smi -q | awk -F: '/Serial Number/{gsub(/^ +/,"",$2);print $2;exit}')
DRV=$(nvidia-smi --query-gpu=driver_version --format=csv,noheader)
PL=$(nvidia-smi --query-gpu=power.limit --format=csv,noheader)
PCIE="gen$(nvidia-smi --query-gpu=pcie.link.gen.current --format=csv,noheader) x$(nvidia-smi --query-gpu=pcie.link.width.current --format=csv,noheader)"
CPU=$(lscpu | awk -F: '/Model name/{gsub(/^ +/,"",$2);print $2;exit}')
RAMSPD=$(sudo dmidecode -t memory 2>/dev/null | awk -F: '/Configured Memory Speed/{gsub(/ /,"",$2);print $2;exit}')
RAMTOT=$(free -g | awk '/^Mem:/{print $2"GiB"}')
COMMIT=$(cd /home/user/llama.cpp-portable && git log -1 --format=%h 2>/dev/null)
BYTES=$(wc -c < "$SRC"); LINES=$(wc -l < "$SRC")
VRAM_USED=$(nvidia-smi --query-gpu=memory.used --format=csv,noheader,nounits | head -1)

read -r -d '' HDR <<EOF || true
<!--
  ============================================================================
  $(basename "$SRC") - generated by a local LLM, not written by a human.

  MODEL      unsloth/GLM-5.2  UD-Q2_K_XL  (~237 GiB, 7 shards)
             751B total params, MoE arch "glm-dsa": 256 experts, 8 routed +
             1 shared active per token, MLA (key/value_length_mla=256),
             DSA lightning-indexer (top_k=2048), native NextN/MTP head
  ENGINE     llama.cpp mainline ${COMMIT}, built for sm_80 / CUDA 12.8
             (NOT ik_llama.cpp -- both ik_llama builds on this box are
             compiled for CUDA arch 120/Blackwell, wrong arch for this
             sm_80 card; mainline gained native glm-dsa + MTP support
             upstream and was rebuilt locally to pick it up)
  HARNESS    opencode, single agentic build task

  HARDWARE   GPU  ${GPU}
                  serial ${SERIAL}, driver ${DRV}, power cap ${PL}, PCIe ${PCIE}
                  ** memory UNLOCKED 8GB -> 64GB via cmpunlocker (GA100 die) **
             CPU  ${CPU}
             RAM  ${RAMTOT} DDR5 @ ${RAMSPD}
             Hybrid CPU+GPU offload via --fit: ~${VRAM_USED} MiB VRAM used at
             steady state, remainder of the ~237 GiB weights resident in RAM.

  SETTINGS   --fit on  --ctx-size 81920  -ctk q8_0 -ctv q8_0  --parallel 1
             --spec-type draft-mtp --spec-draft-n-max 2
             --reasoning-format deepseek --reasoning-budget 10000
             --threads 11 --threads-batch 11  --load-mode none

  OUTPUT     ${BYTES} bytes, ${LINES} lines
  GENERATED  $(date '+%Y-%m-%d %H:%M:%S %Z')

  Pristine copy (no comment block): $(basename "${BASE}").original.html
  Full metrics: ARTIFACT-${LABEL}.md
  ============================================================================
-->
EOF

python3 - "$SRC" "${BASE}_${LABEL}.html" "$HDR" <<'PY'
import re,sys
src,dst,hdr=sys.argv[1],sys.argv[2],sys.argv[3]
s=open(src,encoding='utf-8',errors='replace').read()
m=re.search(r'<!DOCTYPE[^>]*>',s,re.I)
if m:
    out=s[:m.end()]+"\n"+hdr+s[m.end():]
else:
    out=hdr+"\n"+s
open(dst,'w',encoding='utf-8').write(out)
print(f"labelled -> {dst} ({len(out)} bytes)")
PY

{
  echo "# Artifact provenance - $(basename "$SRC")"
  echo
  echo "Generated $(date '+%Y-%m-%d %H:%M:%S %Z') on the unlocked CMP 170HX."
  echo
  echo '## Model'
  echo '- `unsloth/GLM-5.2` **UD-Q2_K_XL** (~237 GiB, 7 shards)'
  echo '- 751B total params, MoE arch `glm-dsa`: 256 experts, 8 routed + 1 shared active/token'
  echo '- MLA (key/value_length_mla=256), DSA lightning-indexer (top_k=2048), native NextN/MTP head'
  echo "- Engine: llama.cpp mainline \`${COMMIT}\`, **sm_80** build, CUDA 12.8"
  echo '- Harness: opencode, single agentic build task'
  echo
  echo '## Hardware'
  echo "- **GPU**: ${GPU} (serial ${SERIAL})"
  echo "  - driver ${DRV}, power cap ${PL}, PCIe ${PCIE}"
  echo '  - **memory unlocked 8 GB -> 64 GB** via cmpunlocker (GA100 die, compute throttle also removed)'
  echo "- **CPU**: ${CPU}"
  echo "- **RAM**: ${RAMTOT} DDR5 @ ${RAMSPD}"
  echo "- Hybrid offload via --fit: ~${VRAM_USED} MiB VRAM used at steady state, remainder of ~237 GiB in system RAM"
  echo
  echo '## Output'
  echo "- ${BYTES} bytes, ${LINES} lines"
  echo '- Comparison, GLM-5.2 on RTX Pro 4000 24GB, ik_llama MTP n_max=2 (2026-07-22): 5.96 tok/s decode'
  echo
  echo '## Measured performance'
  echo '```'
  "$(dirname "$0")/collect-bench-metrics.sh" "$R" 2>/dev/null | sed -n '/THROUGHPUT/,/OUTPUT ARTIFACT/p'
  echo '```'
  echo
  echo '## Caveats'
  echo '- Engine swap for this run: mainline llama.cpp (native glm-dsa/MTP support), not the'
  echo '  ik_llama.cpp build used for the 2026-07-22 baseline -- decode-speed comparisons cross'
  echo '  both an engine change and a VRAM change (24GB -> 64GB), not VRAM alone.'
  echo '- `--spec-draft-n-max 2` was carried over from the ik_llama/24GB sweep as an informed'
  echo '  starting point, not re-swept on this engine/card (a full sweep costs one 237GB reload'
  echo '  per point).'
} > "$R/ARTIFACT-${LABEL}.md"

echo "[$(date '+%F %T')] done:"
ls -la "$R"/*.html "$R/ARTIFACT-${LABEL}.md"

# Also drop a copy alongside the other CMP-170HX cowboy-clue games (deepseek/qwen runs)
# so all model comparisons for this hardware live in one folder.
COLLECTION="/home/user/cowboy-clue benchmark/all-cowboy-clue-games"
mkdir -p "$COLLECTION"
cp -f "${BASE}_${LABEL}.html" "$COLLECTION/"
cp -f "$R/ARTIFACT-${LABEL}.md" "$COLLECTION/"
echo "[$(date '+%F %T')] copied into collection: $COLLECTION/$(basename "${BASE}_${LABEL}.html")"
