#!/usr/bin/env bash
# Wait for the cowboy-clue HTML to be written, then preserve and label it with full
# provenance so the artifact is self-describing months from now.
#
# Produces three things:
#   cowboy_clue.original.html   pristine byte-for-byte as the model wrote it (never touched,
#                               so it stays comparable against the 2026-07-31 run's artifact)
#   cowboy_clue_<label>.html    same content + a provenance comment block, safe to open
#   ARTIFACT-<label>.md         sidecar with hardware, model, engine, settings and measured perf
#
# The comment is injected AFTER the doctype, never before it: content preceding <!DOCTYPE>
# pushes browsers into quirks mode and would change how the game renders.
set -uo pipefail
R="${1:-/home/user/cowboy-clue benchmark/runs/cowboy-clue-cmp170hx}"
WAIT_PID="${2:-}"   # optional: wait for this PID (the agent) to exit first
LABEL="cmp170hx-64gb-unlocked_deepseek-v4-flash-0731-UD-Q8_K_XL_$(date +%Y%m%d)"

# Do NOT hardcode the output filename. The 2026-07-31 run produced cowboy_clue.html but
# this run produced index.html -- the model picks the name, and a fixed filename means the
# labeller waits forever for a file that never appears.
find_html() { ls -S "$R"/*.html 2>/dev/null | grep -v '\.original\.html$' | grep -v "_${LABEL}\.html$" | head -1; }

if [[ -n "$WAIT_PID" ]]; then
    echo "[$(date '+%F %T')] waiting for agent PID $WAIT_PID to exit"
    while kill -0 "$WAIT_PID" 2>/dev/null; do sleep 15; done
    echo "[$(date '+%F %T')] agent exited"
fi

echo "[$(date '+%F %T')] looking for an HTML artifact in $R"
for i in $(seq 1 720); do SRC=$(find_html); [[ -n "${SRC:-}" && -s "$SRC" ]] && break; sleep 10; done
SRC=$(find_html)
[[ -n "${SRC:-}" && -s "$SRC" ]] || { echo "ERROR: no HTML artifact appeared"; exit 1; }

# Wait for the size to stop changing -- the agent may still be revising the file.
prev=0; for i in $(seq 1 40); do
    cur=$(wc -c < "$SRC"); [[ "$cur" == "$prev" ]] && break; prev=$cur; sleep 15
done
echo "[$(date '+%F %T')] settled on $(basename "$SRC"): $(wc -c < "$SRC") bytes"

BASE="${SRC%.html}"
cp -n "$SRC" "${BASE}.original.html"

GPU=$(nvidia-smi --query-gpu=name,memory.total,vbios_version --format=csv,noheader)
DRV=$(nvidia-smi --query-gpu=driver_version --format=csv,noheader)
PL=$(nvidia-smi --query-gpu=power.limit --format=csv,noheader)
PCIE="gen$(nvidia-smi --query-gpu=pcie.link.gen.current --format=csv,noheader) x$(nvidia-smi --query-gpu=pcie.link.width.current --format=csv,noheader)"
CPU=$(lscpu | awk -F: '/Model name/{gsub(/^ +/,"",$2);print $2;exit}')
RAMSPD=$(sudo dmidecode -t memory 2>/dev/null | awk -F: '/Configured Memory Speed/{gsub(/ /,"",$2);print $2;exit}')
RAMTOT=$(free -g | awk '/^Mem:/{print $2"GiB"}')
COMMIT=$(cd /home/user/llama.cpp-portable && git log -1 --format=%h 2>/dev/null)
BYTES=$(wc -c < "$SRC"); LINES=$(wc -l < "$SRC")

read -r -d '' HDR <<EOF || true
<!--
  ============================================================================
  cowboy_clue.html - generated by a local LLM, not written by a human.

  MODEL      unsloth/DeepSeek-V4-Flash-0731  UD-Q8_K_XL  (~151 GiB, 5 shards)
             284B total params / 13B active per token, MoE, arch "deepseek4"
             (MLA + DSA sparse-attention indexer)
  ENGINE     llama.cpp mainline ${COMMIT}, built for sm_80 / CUDA 12.8
  HARNESS    opencode 1.18.13, single agentic build task, one write call

  HARDWARE   GPU  ${GPU}
                  driver ${DRV}, power cap ${PL}, PCIe ${PCIE}
                  ** memory UNLOCKED 8GB -> 64GB via cmpunlocker (GA100 die) **
             CPU  ${CPU}
             RAM  ${RAMTOT} DDR5 @ ${RAMSPD}
             Hybrid CPU+GPU offload: ~63.5 GiB of weights on the GPU,
             the remaining ~87 GiB resident in system RAM.

  SETTINGS   --fit on  --ctx-size 720896  -fa on  -ctk f16 -ctv f16
             --parallel 1  --temp 1.0 --top-p 1.0 --min-p 0.0
             --reasoning on --reasoning-budget 10000  --threads 11  --no-mmap

  OUTPUT     ${BYTES} bytes, ${LINES} lines
  GENERATED  $(date '+%Y-%m-%d %H:%M:%S %Z')

  Pristine copy (no comment block): $(basename "${BASE}").original.html
  Full metrics: ARTIFACT-${LABEL}.md
  ============================================================================
-->
EOF

python3 - "$SRC" "${BASE}_${LABEL}.html" "$HDR" <<'PY'
import re,sys
src,dst,hdr=sys.argv[1],sys.argv[2],sys.argv[3]
s=open(src,encoding='utf-8',errors='replace').read()
m=re.search(r'<!DOCTYPE[^>]*>',s,re.I)
if m:  # after the doctype -- anything before it forces quirks mode
    out=s[:m.end()]+"\n"+hdr+s[m.end():]
else:
    out=hdr+"\n"+s
open(dst,'w',encoding='utf-8').write(out)
print(f"labelled -> {dst} ({len(out)} bytes)")
PY

{
  echo "# Artifact provenance - cowboy_clue.html"
  echo
  echo "Generated $(date '+%Y-%m-%d %H:%M:%S %Z') on the unlocked CMP 170HX."
  echo
  echo '## Model'
  echo '- `unsloth/DeepSeek-V4-Flash-0731` **UD-Q8_K_XL** (~151 GiB, 5 shards)'
  echo '- 284B total / 13B active per token, MoE, arch `deepseek4` (MLA + DSA sparse attention)'
  echo "- Engine: llama.cpp mainline \`${COMMIT}\`, **sm_80** build, CUDA 12.8"
  echo '- Harness: opencode 1.18.13, single agentic build task'
  echo
  echo '## Hardware'
  echo "- **GPU**: ${GPU}"
  echo "  - driver ${DRV}, power cap ${PL}, PCIe ${PCIE}"
  echo '  - **memory unlocked 8 GB -> 64 GB** via cmpunlocker (GA100 die, compute throttle also removed)'
  echo "- **CPU**: ${CPU}"
  echo "- **RAM**: ${RAMTOT} DDR5 @ ${RAMSPD}"
  echo '- Hybrid offload: ~63.5 GiB weights on GPU, ~87 GiB resident in system RAM'
  echo
  echo '## Output'
  echo "- ${BYTES} bytes, ${LINES} lines"
  echo '- Comparison, 2026-07-31 on 2x RTX PRO 4000 24GB + DDR5-3600: 2965 s, 44,092 bytes, 1,211 lines'
  echo
  echo '## Measured performance'
  echo '```'
  "$(dirname "$0")/collect-bench-metrics.sh" "$R" 2>/dev/null | sed -n '/THROUGHPUT/,/OUTPUT ARTIFACT/p'
  echo '```'
  echo
  echo '## Caveats'
  echo '- `cpu-temp-guard.service` was enabled at 14:10, ~55 min into this run, capping CPU'
  echo '  frequency to hold <=90 C. Timings after that point reflect a throttled CPU.'
  echo '- Thread affinity was NOT yet applied on this run: all work landed on CCD0'
  echo '  (117% busy vs 10% on CCD1). Later runs use `--cpu-range 0-11 --cpu-strict 1`.'
  echo '- Two brief operator perturbations: `nvidia-smi -lgc 1400` (~1 s) and a 3000 MHz'
  echo '  CPU frequency cap (~2 s) while validating tooling mid-run.'
} > "$R/ARTIFACT-${LABEL}.md"

echo "[$(date '+%F %T')] done:"
ls -la "$R"/*.html "$R/ARTIFACT-${LABEL}.md"
